### ISSUE TITLE
The default font sizes for the website are actually a bit tiny.

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/openrefine.org#336]
We can increase the font-size globally quite easily so that things "just work" across all devices and systems.

Currently the default for Docusaurus Theme Classic behind the scenes are

`--ifm-font-size-base: 100%`
`--ifm-code-font-size: 90%;`

But ideally should be something like
`--ifm-font-size-base: 110%`  or slightly larger depending on opinions.

This can be added into the `/src/css/custom.css` file like so:

```css
:root {
  --ifm-font-size-base: 110%;
  --ifm-code-font-size: 100%;
  --ifm-color-primary: #25c2a0;
  etc.
}
```
